name: Compose Jepsen and Run a Test

on:
  workflow_dispatch:
    inputs:
      test-org:
        description: Organization
        required: true
      test-repo:
        description: Repository
        required: true
      test-ref:
        description: Reference
        required: true
      workload:
        description: Workload
        required: true
      nemesis:
        description: Nemesis
        required: true
      cli-opts:
        description: --cli-opts
        required: false
  workflow_call:
    inputs:
      test-org:
        type: string
        description: Organization
        required: true
      test-repo:
        type: string
        description: Repository
        required: true
      test-ref:
        type: string
        description: Reference
        required: true
      workload:
        type: string
        description: Workload
        required: true
      nemesis:
        type: string
        description: Nemesis
        required: true
      cli-opts:
        type: string
        description: "--cli-opts"
        required: false

jobs:
  compose-jepsen-run-test:
    runs-on: ubuntu-latest

    steps:          
      - name: Clone jepsen and ${{ inputs.test-repo }}
        run: |
          git clone --depth 1 --branch main https://github.com/nurturenature/jepsen-docker.git
          git clone --depth 1 --branch jepsen-docker https://github.com/nurturenature/jepsen.git
          git clone --depth 1 --branch ${{ inputs.test-ref }} https://github.com/${{ inputs.test-org }}/${{ inputs.test-repo }}.git

      - name: Docker Compose a Jepsen Cluster
        run: |
          JEPSEN_ROOT="$(pwd)/${{ inputs.test-repo }}" && export JEPSEN_ROOT
          cd jepsen/docker
          ./bin/up --registry ghcr.io/nurturenature/jepsen-docker/ --daemon --dev --compose ../../jepsen-docker/docker-compose.github-config.yml
          cd ../..

      - name: Docker Logs
        run: |
          echo "jepsen-n1 docker logs:"
          docker logs --details jepsen-n1
          echo "jepsen-control docker logs:"
          docker logs --details jepsen-control
          echo "Docker images:"
          docker images
          echo "Docker ps:"
          docker ps

      - name: Test Jepsen Cluster
        run: |
          docker exec --env BASH_ENV=/root/.bashrc jepsen-control bash -c "ssh root@n1 hostname"
          
      - name: ${{ inputs.test-repo }} - ${{ inputs.workload }} - ${{ inputs.nemesis }}
        run: |
          docker exec --env BASH_ENV=/root/.bashrc jepsen-control bash -c \
            "lein run test --workload ${{ inputs.workload }} --nemesis ${{ inputs.nemesis }} ${{ inputs.cli-opts }}"
 
      - name: Jepsen Test Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.test-repo }}-${{ inputs.workload }}-${{ inputs.nemesis }}
          path: |
            **/${{ inputs.test-repo }}/store
            !**/current/
            !**/latest/
