name: Publish Jepsen Images

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-jepsen-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone jepsen-docker
        run: |
          gh repo clone nurturenature/jepsen-docker
          
      - name: Build Jepsen Images
        run: |
          cd jepsen-docker
          docker build -t jepsen-setup   ./jepsen-setup
          docker build -t jepsen-node    ./jepsen-node
          docker build -t jepsen-control ./jepsen-control
          cd ..

      - name: Docker Images
        run: |
          echo Built docker images:
          docker images

      - name: Login to Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Images
        run: |
          docker tag jepsen-setup   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-setup
          docker tag jepsen-node    ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-node
          docker tag jepsen-control ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-control
          echo Tagged docker images:
          docker images

      - name: Push Images
        run: |
          docker push -q ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-setup
          docker push -q ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-node
          docker push -q ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-control
