name: Publish Jepsen Images

on:
  schedule:
    - cron: "15 0 * * 0"  # every Sunday at 00:15
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  publish-jepsen-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout jepsen-docker
        uses: actions/checkout@v5
        
      - name: Build Jepsen Images
        run: |
          cd $GITHUB_WORKSPACE
          docker build -t jepsen-setup:bookworm   ./jepsen-setup
          docker build -t jepsen-node:bookworm    ./jepsen-node
          docker build -t jepsen-control:bookworm ./jepsen-control

      - name: List Docker Images
        run: |
          echo Built docker images:
          docker images

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Images
        run: |
          docker tag jepsen-setup:bookworm   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-setup:bookworm
          docker tag jepsen-node:bookworm    ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-node:bookworm
          docker tag jepsen-control:bookworm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-control:bookworm
          echo Tagged docker images:
          docker images

      - name: Push Images
        run: |
          docker push -q ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-setup:bookworm
          docker push -q ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-node:bookworm
          docker push -q ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/jepsen-control:bookworm

      - name: Delete Old jepsen-setup Images
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'jepsen-docker/jepsen-setup:bookworm'
          package-type: 'container'
          delete-only-untagged-versions: 'true'

      - name: Delete Old jepsen-node Images
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'jepsen-docker/jepsen-node:bookworm'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
          
      - name: Delete Old jepsen-control Images
        uses: actions/delete-package-versions@v5
        with: 
          package-name: 'jepsen-docker/jepsen-control:bookworm'
          package-type: 'container'
          delete-only-untagged-versions: 'true'
